config/routes.rb
Rails.application.routes.draw do

  resources :classrooms
  devise_for :admins
  get 'admin/home'

  devise_for :installs
  resources :tutors
  resources :students
  devise_for :users 

  resources :surveys
  root 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'

  resources :bookstores do
    member do
      get :purchase
      get :cashier
    end
  end
  resources :courses

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5, maximum: 150 }
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :course
  belongs_to :tutor
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :students, :through => :classroom

  validates :title, presence: true, length: { minimum: 10, maximum: 150 }
  
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :courses, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  has_many :classrooms
  has_many :courses, :through => :classroom
  has_many :students, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :students
  has_many :tutors
  has_one  :admin
  validates :email, presence: true, length: { minimun: 10, maximum: 250}

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def home
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:course_id, :course_id, :tutor_id, :tutor_id, :tutor_last_name, :tutor_first_name, :student_id, :student_id, :student_last_name, :student_first_name)
    end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
    @tutors = Tutor.paginate(page: params[:page], per_page: 3)
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:first_name, :last_name, :email, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/classrooms/_classrooms.html.erb
<div align="center">
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <%= will_paginate @products %>
</div>

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>

  <div class="field">
    <%= f.label :tutor_id %><br>
    <%= f.number_field :tutor_id %>
  </div>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Listing Classrooms</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Course :id</th>
      <th>Tutor :id</th>
      <th>:last name</th>
      <th>:first name</th>
      <th>Student :id </th>
      <th>:last name</th>
      <th>:first name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td>Unit: <%= classroom.course_id %></td>
        <td><%= classroom.tutor_id %></td>
        <td><%= classroom.tutor.last_name %></td>
        <td><%= classroom.tutor.first_name %></td>
        <td><%= classroom.student_id%></td>
        <td><%= classroom.student.last_name %></td>
        <td><%= classroom.student.first_name %></td>
        <td>| <%= link_to 'Show', classroom %> |
        <%= link_to 'Edit', edit_classroom_path(classroom) %> |
        <%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %> |
      </tr>
    <% end %>
  </tbody>
</table>

<br>
| <%= link_to 'New Classroom', new_classroom_path %> |
<%= link_to 'Courses', courses_path %> |
<%= link_to 'Students', students_path %> |
<%= link_to 'Tutors', tutors_path %> |

app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Course:</strong>
  <%= @classroom.course_id %>
</p>



<p>
  <strong>Tutor:</strong>
  <%= @classroom.tutor_id %>
</p>

<p>
  <strong>Tutor last name:</strong>
  <%= @classroom.tutor.last_name %>
</p>

<p>
  <strong>Tutor first name:</strong>
  <%= @classroom.tutor.first_name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @classroom.student_id %>
</p>

<p>
  <strong>Student last name:</strong>
  <%= @classroom.student.last_name %>
</p>

<p>
  <strong>Student first name:</strong>
  <%= @classroom.student.first_name %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>