config/routes.rb
Rails.application.routes.draw do

  resources :classrooms
  devise_for :admins
  get 'admin/home'

  devise_for :installs
  resources :tutors
  resources :students
  devise_for :users 

  resources :surveys
  root 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'

  resources :bookstores do
    member do
      get :purchase
      get :cashier
    end
  end
  resources :courses

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5, maximum: 150 }
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :course
  belongs_to :tutor
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :students, :through => :classroom

  validates :title, presence: true, length: { minimum: 10, maximum: 150 }
  
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :courses, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  has_many :classrooms
  has_many :courses, :through => :classroom
  has_many :students, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :students
  has_many :tutors
  has_one  :admin
  validates :email, presence: true, length: { minimun: 10, maximum: 250}

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/admin/home.html.erb
<h1>Admin Dashboard</h1>
<ul>
  <li><%= link_to 'Classroom', classrooms_path %></li>
  <li><%= link_to 'Tutors', tutors_path %></li>
  <li><%= link_to 'Students', students_path %></li>
  <li><%= link_to 'Survey', surveys_path %></li>
  <li><%= link_to 'Courses', courses_path %></li>
  <li><%= link_to 'Bookstore',  bookstores_path  %></li>
</ul>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
     <p> Copyright © owentaffe@gmail.com</p>
    </small>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %> |
          <%= link_to "About", about_path %> |
          <%= link_to 'Contact', contact_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-coll                                                      apse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "OnLine College", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><%= link_to 'Courses', courses_path %></li>
        <li><%= link_to 'Survey', new_survey_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'bookstore', bookstores_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Classroom', classrooms_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Students', students_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Tutors', tutors_path %></li>
          </ul>
        </li>               
      </ul>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
         <li><%= link_to "Sign up", new_user_registration_path %></li>
         <li><%= link_to "log in", user_session_path %></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
 <%= render 'layouts/navigation' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>