config/routes.rb
Rails.application.routes.draw do

  resources :classrooms
  devise_for :admins
  get 'admin/home'

  devise_for :installs
  resources :tutors
  resources :students
  devise_for :users 

  resources :surveys
  root 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'

  resources :bookstores do
    member do
      get :purchase
      get :cashier
    end
  end
  resources :courses

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5, maximum: 150 }
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :course
  belongs_to :tutor
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :students, :through => :classroom

  validates :title, presence: true, length: { minimum: 10, maximum: 150 }
  
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :courses, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  has_many :classrooms
  has_many :courses, :through => :classroom
  has_many :students, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :students
  has_many :tutors
  has_one  :admin
  validates :email, presence: true, length: { minimun: 10, maximum: 250}

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def home
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
    @surveys = Survey.paginate(page: params[:page], per_page: 5)
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:Q1, :Q2, :Q3, :Q4, :Q5, :Q6, :Q)
    end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
    @tutors = Tutor.paginate(page: params[:page], per_page: 3)
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:first_name, :last_name, :email, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/surveys/_form.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-10">
  <%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li align="center"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Q1 %>
    <strong>: Overall, how well does our website meet your needs?</strong><br>
    <%= f.number_field :Q1 %>
  </div>
  <div class="field">
    <%= f.label :Q2 %>
    <strong>: How easy was it to find what you were looking for on our website? </strong><br>
    <%= f.number_field :Q2 %>
  </div>
  <div class="field">
    <%= f.label :Q3 %>
    <strong>:   Did it take you more or less time than you expected to find what you were looking for on our website?
    </strong><br>
    <%= f.number_field :Q3 %>
  </div>
  <div class="field">
    <%= f.label :Q4 %>
    <strong>:   How visually appealing is our website?</strong><br>
    <%= f.number_field :Q4 %>
  </div>
  <div class="field">
    <%= f.label :Q5 %>
    <strong>: How easy is it to understand the information on our website? </strong><br>
    <%= f.number_field :Q5 %>
  </div>
  <div class="field">
    <%= f.label :Q6 %>
    <strong>: How much do you trust the information on our website? </strong><br>
    <%= f.number_field :Q6 %>
  </div>
  <div class="field">
    <%= f.label :Q %>7
    <strong>:  Do you have any other comments about how we can improve our website?</strong><br>
    <div class="row">
      <div class="col-xs-8">
        <%= f.text_area :Q, class: "form-control", placeholder: "Place yor comments heres", autofocus: true %>
      </div>
    </div>
  </div>
 <button type="submit" class="btn btn-default">Submit</button>
  </div>
</div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
  <h1>Listing Surveys</h1>
  <%= will_paginate %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
      <th>Q7</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.Q1 %></td>
        <td><%= survey.Q2 %></td>
        <td><%= survey.Q3 %></td>
        <td><%= survey.Q4 %></td>
        <td><%= survey.Q5 %></td>
        <td><%= survey.Q6 %></td>
        <td><%= survey.Q %></td>
        <td><%= link_to 'Show', survey %> |
        <%= link_to 'Edit', edit_survey_path(survey) %> |
        <%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div align="center">
  <%= will_paginate %>
</div>
<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1 align="center">New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1: Overall, how well does our website meet your needs?  :</strong>

  <%= @survey.Q1 %>
</p>

<p>
  <strong>Q2:  How easy was it to find what you were looking for on our website? :</strong>
  <%= @survey.Q2 %>
</p>

<p>
  <strong>Q3:  Did it take you more or less time than you expected to find what you were looking for on our website? :</strong>
  <%= @survey.Q3 %>
</p>

<p>
  <strong>Q4:  How visually appealing is our website? :</strong>
  <%= @survey.Q4 %>
</p>

<p>
  <strong>Q5: How easy is it to understand the information on our website? :</strong>
  <%= @survey.Q5 %>
</p>

<p>
  <strong>Q6: How much do you trust the information on our website? :</strong>
  <%= @survey.Q6 %>
</p>

<p>
  <strong>Q7: Do you have any other comments about how we can improve our website?</strong><br>
  <%= @survey.Q %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>