config/routes.rb
Rails.application.routes.draw do

  resources :classrooms
  devise_for :admins
  get 'admin/home'

  devise_for :installs
  resources :tutors
  resources :students
  devise_for :users 

  resources :surveys
  root 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'

  resources :bookstores do
    member do
      get :purchase
      get :cashier
    end
  end
  resources :courses

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/models/bookstore.rb
class Bookstore < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5, maximum: 150 }
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :course
  belongs_to :tutor
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :students, :through => :classroom

  validates :title, presence: true, length: { minimum: 10, maximum: 150 }
  
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  has_many :tutors, :through => :classroom 
  has_many :courses, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  has_many :classrooms
  has_many :courses, :through => :classroom
  has_many :students, :through => :classroom

  validates :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :first_name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :students
  has_many :tutors
  has_one  :admin
  validates :email, presence: true, length: { minimun: 10, maximum: 250}

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def home
  end
end

app/controllers/bookstores_controller.rb
class BookstoresController < ApplicationController

  before_action :set_bookstore, only: [:show, :edit, :update, :destroy, :purchase]

  # GET /bookstores
  # GET /bookstores.json
  def index
    @bookstore = Bookstore.all
    @bookstores = Bookstore.paginate(page: params[:page], per_page: 3)
  end

  # GET /bookstores/1
  # GET /bookstores/1.json
  def show
  end

  # GET /bookstores/new
  def new
    @bookstore = Bookstore.new
  end

  # GET /bookstores/1/edit
  def edit
  end

  def purchase

  end

  # POST /bookstores
  # POST /bookstores.json
  def create
    @bookstore = Bookstore.new(bookstore_params)
    respond_to do |format|
      if @bookstore.save
        format.html { redirect_to @bookstore, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @bookstore }
      else
        format.html { render :new }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookstores/1
  # PATCH/PUT /bookstores/1.json
  def update
    cd 
    respond_to do |format|
      if @bookstore.update(bookstore_params)
        format.html { redirect_to @bookstore, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookstore }
      else 
        format.html { render :edit }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstores/1
  # DELETE /bookstores/1.json
  def destroy
    @bookstores.destroy
    respond_to do |format|
      format.html { redirect_to bookstores_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookstore
      @bookstore = Bookstore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookstore_params
      params.require(:bookstore).permit(:title, :description, :author, :price)
    end
    def purchase_params
      params.require(:bookstore).permit(:titles, :description, :author, :price)
    end
  end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
    @tutors = Tutor.paginate(page: params[:page], per_page: 3)
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:first_name, :last_name, :email, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/bookstores/_form.html.erb
<div class='row'>
  <div class='col-xs-offset-2 col-xs-8'>
    <%= form_for(@bookstore, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
    <div class="form-group">
      <div class="control-label  col-xs-2">
        <%= f.label :title %>
      </div>
      <div class="control-label  col-xs-8">
        <%= f.text_field :title, class: "form-control", placeholder: "title", autofocus: true %>
      </div>
    </div>
      <div class="form-group">
        <div class="control-label  col-xs-2">
          <%= f.label :Description %>
        </div>
        <div class="control-label  col-xs-8">
          <%= f.text_area :description, class: "form-control", placeholder: "Description", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
      <div class="control-label  col-xs-2">
        <%= f.label :Author %>
      </div>
      <div class="control-label  col-xs-8">
        <%= f.text_field :author, class: "form-control", placeholder: "Author", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label  col-xs-2">
        <%= f.label :Price %>
      </div>
      <div class="control-label  col-xs-8">
        <%= f.text_field :price, class: "form-control", placeholder: "Price", autofocus: true %>
      </div>
    </div><br>
    <div class="col-xs-offset-2 col-xs-2">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
  
  <% end %>
</div>

app/views/bookstores/_parshow.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-heading"><strong>Title: <%= @bookstore.title %></strong></div>
</div>
  <div class="panel panel-default">
    <div class="panel-body">
      <strong>Description: </strong><%= @bookstore.description %><br>
      <strong>Author: </strong><%= @bookstore.author %><br>
      <strong>Price:</strong><%= @bookstore.price %>
    </div>
</div>

app/views/bookstores/cashier.html.erb
<h1 align="center">Cashier will be here shortly</h1>

<h4 align="center">
  <p>You can set up payment by</p>
  <p>adding a gem called stripe </p>
  <p>go to https://github.com/stripe/stripe-ruby</p>
  <p>and follow the installion instructions</p>
</h4>

app/views/bookstores/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookstore %> |
<%= link_to 'Back', bookstores_path %>

app/views/bookstores/index.html.erb
<div align="center">
  <h1>Listing books</h1>
  <p><%= link_to 'Add new book Here', new_bookstore_path %></p>
  <%= will_paginate %>
</div>
  <% @bookstores.each do |bookstore| %>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10 ">
      <div class="well well-lg">
        <div class="book-title">
          <h1 align="center"><strong>Title: </strong>
            <%= link_to bookstore.title, bookstore_url(bookstore) %>
          </h1>
        </div>
        <div class="article-body">
          <h3>Description:</h3>
           <p><%= bookstore.description %></p><br>
          <p>Author: <%= bookstore.author %></p><br>
          <p>Price: <%= bookstore.price %></p>
         </div><br>

       <%= link_to 'Show', bookstore %>
       <%= link_to 'Edit', edit_bookstore_path(bookstore) %>
       <%= link_to 'Destroy', bookstore, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
<div align="center"><%= will_paginate %></div>

    <% end %>
  <div class="col-xs-4 col-xs-offset-2">
    <%= link_to 'Add New Book Here', new_bookstore_path %>
  </div>
<br>

app/views/bookstores/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', bookstores_path %>

app/views/bookstores/purchase.html.erb
<h1 align="center">Purchase your Book here</h1>

<%= render 'parshow' %>
<div class="row">
  <div class="col-md=8 cpl-md-offset-2">
  <form class="form-horizontal">
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Full Name</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Name">
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Address Line 1</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Address">
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Address Line 2</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Address">
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">City/Town</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="City/Town">
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">County</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="County">
      </div>
    </div>
     <div class="form-group">
      <label for="inputPassword3" class="col-sm-2 control-label">Country</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" id="inputPassword3" placeholder="Country">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword3" class="col-sm-2 control-label">Phone Number</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" id="inputPassword3" placeholder="Phone Number">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to 'Pay with Credit Card', cashier_bookstore_path(@bookstore), class: "btn btn-success btn-lg" %>
        <%= link_to 'Pay with Pay Pal', cashier_bookstore_path(@bookstore), class: "btn btn-success btn-lg" %>
      </div>
    </div>
  </form>
  </div>
</div>

app/views/bookstores/show.html.erb
<h1 align="center">Book details</h1>
    <%= render 'parshow' %>
  <div class="panel-footer">
    <p><%= link_to 'Buy', purchase_bookstore_path(@bookstore), class: "btn btn-success btn-lg" %> |
    <%= link_to 'Edit', edit_bookstore_path %> |
    <%= link_to 'Back', bookstores_path %></p>
  </div>